version: '3.9'
services:
  auth:
    image: quay.io/keycloak/keycloak:19.0.3
    container_name: auth
    volumes:
      - ./keycloak/data:/var/tmp
      - ./keycloak/startup-scripts/init.sh:/docker-entrypoint-sh/init.sh
    entrypoint: sh -c "/docker-entrypoint-sh/init.sh"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
    ports:
      - 8180:8180
    networks:
      acad-net:
networks:
  acad-net:
